/* V001 - Create database */
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

USE master;
GO

IF DB_ID(N'ClinicDB') IS NULL
    CREATE DATABASE ClinicDB ;
GO

ALTER DATABASE ClinicDB SET RECURSIVE_TRIGGERS OFF;
GO
